tests:
### MMEM testing
  - name: mmem-test
    timeout: 60
    devices:
      - name: receiver
        programdir: examples/mmem-test
        program: mmem-test
        instrument: [examples/mmem-test/mmem-test.c,core/lib/mmem.c]
        debug: [examples/mmem-test/mmem-test.c]
        cflags: "-fno-inline -DPROFILES_CONF_MAX=100 -DPROFILES_CONF_STACKSIZE=30"
        graph_options: ""
  - name: mmem-test-uninstr
    timeout: 60
    devices:
      - name: receiver
        programdir: examples/mmem-test
        program: mmem-test
        instrument: []
        debug: [examples/mmem-test/mmem-test.c]
        cflags: ""
        graph_options: ""
