tests:
### Test latency
  - name: pingpong
    timeout: 900
    devices:
      - name: sender
        programdir: examples/uDTN/pingpong
        program: uDTN-pingpong
        instrument: [examples/uDTN/pingpong/uDTN-pingpong.c,platform/inga/*.c,core/net/uDTN/*.c]
        debug: []
        cflags: "-DNETSTACK_CONF_MAC=nullmac_driver -DNETSTACK_CONF_RDC=nullrdc_driver -D__DELAY_BACKWARD_COMPATIBLE__ -fno-inline  -DCONF_MODE=1 -DCONF_DEST_NODE=$RECEIVER -DPROFILES_CONF_MAX=100 -DPROFILES_CONF_STACKSIZE=30"
        graph_options: ""
      - name: receiver
        programdir: examples/uDTN/pingpong
        program: uDTN-pingpong
        instrument: [examples/uDTN/pingpong/uDTN-pingpong.c,platform/inga/*.c,core/net/uDTN/*.c]
        debug: []
        cflags: "-DNETSTACK_CONF_MAC=nullmac_driver -DNETSTACK_CONF_RDC=nullrdc_driver -D__DELAY_BACKWARD_COMPATIBLE__ -fno-inline -DCONF_MODE=0 -DCONF_DEST_NODE=$SENDER -DPROFILES_CONF_MAX=100 -DPROFILES_CONF_STACKSIZE=30"
        graph_options: ""
  - name: pingpong-uninstr
    timeout: 900
    devices:
      - name: sender
        programdir: examples/uDTN/pingpong
        program: uDTN-pingpong
        instrument: []
        debug: []
        cflags: "-DNETSTACK_CONF_MAC=nullmac_driver -DNETSTACK_CONF_RDC=nullrdc_driver -fno-inline -DCONF_MODE=1 -DCONF_DEST_NODE=$RECEIVER"
        graph_options: ""
      - name: receiver
        programdir: examples/uDTN/pingpong
        program: uDTN-pingpong
        instrument: []
        debug: []
        cflags: "-DNETSTACK_CONF_MAC=nullmac_driver -DNETSTACK_CONF_RDC=nullrdc_driver -fno-inline -DCONF_MODE=0 -DCONF_DEST_NODE=$SENDER"
        graph_options: ""
### Test latency PDS
  - name: pingpong-pds
    timeout: 3600
    devices:
      - name: sender
        programdir: examples/uDTN/pingpong
        program: uDTN-pingpong
        instrument: [examples/uDTN/pingpong/uDTN-pingpong.c,platform/inga/*.c,core/net/uDTN/*.c]
        debug: []
        cflags: "-DCONF_DISCOVERY_SCHEDULER=discovery_scheduler_pattern -DNETSTACK_CONF_RDC=discovery_aware_rdc_driver -D__DELAY_BACKWARD_COMPATIBLE__ -fno-inline  -DCONF_MODE=1 -DCONF_DEST_NODE=$RECEIVER -DPROFILES_CONF_MAX=100 -DPROFILES_CONF_STACKSIZE=30"
        graph_options: ""
      - name: receiver
        programdir: examples/uDTN/pingpong
        program: uDTN-pingpong
        instrument: [examples/uDTN/pingpong/uDTN-pingpong.c,platform/inga/*.c,core/net/uDTN/*.c]
        debug: []
        cflags: "-DCONF_DISCOVERY_SCHEDULER=discovery_scheduler_pattern -DNETSTACK_CONF_RDC=discovery_aware_rdc_driver -D__DELAY_BACKWARD_COMPATIBLE__ -fno-inline -DCONF_MODE=0 -DCONF_DEST_NODE=$SENDER -DPROFILES_CONF_MAX=100 -DPROFILES_CONF_STACKSIZE=30"
        graph_options: ""
  - name: pingpong-pds-uninstr
    timeout: 3600
    devices:
      - name: sender
        programdir: examples/uDTN/pingpong
        program: uDTN-pingpong
        instrument: []
        debug: []
        cflags: "-DCONF_DISCOVERY_SCHEDULER=discovery_scheduler_pattern -DNETSTACK_CONF_RDC=discovery_aware_rdc_driver -fno-inline -DCONF_MODE=1 -DCONF_DEST_NODE=$RECEIVER"
        graph_options: ""
      - name: receiver
        programdir: examples/uDTN/pingpong
        program: uDTN-pingpong
        instrument: []
        debug: []
        cflags: "-DCONF_DISCOVERY_SCHEDULER=discovery_scheduler_pattern -DNETSTACK_CONF_RDC=discovery_aware_rdc_driver -fno-inline -DCONF_MODE=0 -DCONF_DEST_NODE=$SENDER"
        graph_options: ""
### Test latency ContikiMAC
  - name: pingpong-contikimac
    timeout: 900
    devices:
      - name: sender
        programdir: examples/uDTN/pingpong
        program: uDTN-pingpong
        instrument: [examples/uDTN/pingpong/uDTN-pingpong.c,platform/inga/*.c,core/net/uDTN/*.c]
        debug: []
        cflags: "-DNETSTACK_CONF_MAC=csma_driver -DNETSTACK_CONF_RDC=contikimac_driver -D__DELAY_BACKWARD_COMPATIBLE__ -fno-inline  -DCONF_MODE=1 -DCONF_DEST_NODE=$RECEIVER -DPROFILES_CONF_MAX=100 -DPROFILES_CONF_STACKSIZE=30"
        graph_options: ""
      - name: receiver
        programdir: examples/uDTN/pingpong
        program: uDTN-pingpong
        instrument: [examples/uDTN/pingpong/uDTN-pingpong.c,platform/inga/*.c,core/net/uDTN/*.c]
        debug: []
        cflags: "-DNETSTACK_CONF_MAC=csma_driver -DNETSTACK_CONF_RDC=contikimac_driver -D__DELAY_BACKWARD_COMPATIBLE__ -fno-inline -DCONF_MODE=0 -DCONF_DEST_NODE=$SENDER -DPROFILES_CONF_MAX=100 -DPROFILES_CONF_STACKSIZE=30"
        graph_options: ""
  - name: pingpong-contikimac-uninstr
    timeout: 900
    devices:
      - name: sender
        programdir: examples/uDTN/pingpong
        program: uDTN-pingpong
        instrument: []
        debug: []
        cflags: "-DNETSTACK_CONF_MAC=csma_driver -DNETSTACK_CONF_RDC=contikimac_driver -fno-inline -DCONF_MODE=1 -DCONF_DEST_NODE=$RECEIVER"
        graph_options: ""
      - name: receiver
        programdir: examples/uDTN/pingpong
        program: uDTN-pingpong
        instrument: []
        debug: []
        cflags: "-DNETSTACK_CONF_MAC=csma_driver -DNETSTACK_CONF_RDC=contikimac_driver -fno-inline -DCONF_MODE=0 -DCONF_DEST_NODE=$SENDER"
        graph_options: ""
### Test latency loopback
  - name: pingpong-loopback
    timeout: 900
    devices:
      - name: receiver
        programdir: examples/uDTN/pingpong
        program: uDTN-pingpong
        instrument: [examples/uDTN/pingpong/uDTN-pingpong.c,platform/inga/*.c,core/net/uDTN/*.c]
        debug: []
        cflags: "-DNETSTACK_CONF_MAC=nullmac_driver -DNETSTACK_CONF_RDC=nullrdc_driver -D__DELAY_BACKWARD_COMPATIBLE__ -fno-inline -DPROFILES_CONF_MAX=100 -DPROFILES_CONF_STACKSIZE=30"
        graph_options: ""
  - name: pingpong-loopback-uninstr
    timeout: 900
    devices:
      - name: receiver
        programdir: examples/uDTN/pingpong
        program: uDTN-pingpong
        instrument: []
        debug: []
        cflags: "-DNETSTACK_CONF_MAC=nullmac_driver -DNETSTACK_CONF_RDC=nullrdc_driver -fno-inline"
        graph_options: ""
