tests:
### Test latency
  - name: pingpong
    timeout: 900
    devices:
      - name: sender
        programdir: examples/uDTN/pingpong
        program: uDTN-pingpong
        instrument: [examples/uDTN/pingpong/uDTN-pingpong.c,platform/inga/*.c,core/net/uDTN/*.c]
        debug: []
        cflags: "-fno-inline  -DCONF_MODE=1 -DCONF_DEST_NODE=$RECEIVER -DPROFILES_CONF_MAX=100 -DPROFILES_CONF_STACKSIZE=30"
        graph_options: ""
      - name: receiver
        programdir: examples/uDTN/pingpong
        program: uDTN-pingpong
        instrument: [examples/uDTN/pingpong/uDTN-pingpong.c,platform/inga/*.c,core/net/uDTN/*.c]
        debug: []
        cflags: "-fno-inline -DCONF_MODE=0 -DCONF_DEST_NODE=$SENDER -DPROFILES_CONF_MAX=100 -DPROFILES_CONF_STACKSIZE=30"
        graph_options: ""
  - name: pingpong-uninstr
    timeout: 900
    devices:
      - name: sender
        programdir: examples/uDTN/pingpong
        program: uDTN-pingpong
        instrument: []
        debug: []
        cflags: "-fno-inline -DCONF_MODE=1 -DCONF_DEST_NODE=$RECEIVER"
        graph_options: ""
      - name: receiver
        programdir: examples/uDTN/pingpong
        program: uDTN-pingpong
        instrument: []
        debug: []
        cflags: "-fno-inline -DCONF_MODE=0 -DCONF_DEST_NODE=$SENDER"
        graph_options: ""
### Test latency loopback
  - name: pingpong-loopback
    timeout: 900
    devices:
      - name: receiver
        programdir: examples/uDTN/pingpong
        program: uDTN-pingpong
        instrument: [examples/uDTN/pingpong/uDTN-pingpong.c,platform/inga/*.c,core/net/uDTN/*.c]
        debug: []
        cflags: "-fno-inline -DPROFILES_CONF_MAX=100 -DPROFILES_CONF_STACKSIZE=30"
        graph_options: ""
  - name: pingpong-loopback-uninstr
    timeout: 900
    devices:
      - name: receiver
        programdir: examples/uDTN/pingpong
        program: uDTN-pingpong
        instrument: []
        debug: []
        cflags: "-fno-inline"
        graph_options: ""
