tests:
### Accelerometer test
  - name: sensor-acc
    timeout: 1200
    devices:
      - name: receiver
        programdir: examples/inga_tests/sensor-tests
        program: acc-test
        instrument: []
        debug: []
        cflags: "-fno-inline"
        graph_options: ""
### Gyroscope test
  - name: sensor-gyro
    timeout: 1200
    devices:
      - name: receiver
        programdir: examples/inga_tests/sensor-tests
        program: gyro-test
        instrument: []
        debug: []
        cflags: "-fno-inline"
        graph_options: ""
### Battery test
  - name: sensor-battery
    timeout: 1200
    devices:
      - name: receiver
        programdir: examples/inga_tests/sensor-tests
        program: battery-test
        instrument: []
        debug: []
        cflags: "-fno-inline"
        graph_options: ""
